# https://docs.github.com/code-security/dependabot/working-with-dependabot/dependabot-options-reference
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
